nlamirault/gotest.el

gotest.el

this PR fixes the problem when there are spaces in file path: `buffer-file-name` should be proper shell escaped

escape file path in go command

---

gotest.el
test/go_test.go
test/gotest-test.el

Suite tests need special handling because they are acutally methods and
not top level functions. This commit also refactors
go-test-get-current-test to use regular expression groups. Closes #17.

Add support for github.com/stretchr/testify/suite

---

gotest.el

Because this package uses cl-lib macro(cl-loop), not cl.el.
cl-lib is bundled since Emacs 24.3. And loading cl.el at runtime causes byte-compile warning.

Load cl-lib.el instead of cl.el

---

gotest.el
test/gotest-test.el
test/gotest-version-test.el

- Add check for project "src" directory
- Assume not a gb project if go-test-gb-command is not found in
exec-path
- Add 'go-test-' prefix to gb-command
- Ignore cask warnings in version test

Fix gb project detection

---

gotest.el

this allows users with fish as their login shell
to run go-test-current-test
Without the patch users see an error like:
```
go test -run testName$
Expected a variable name after this $.
fish: go test -run testName$
```

for fish shell compatibility, strictly escape $

---

gotest.el

Sometimes I need to do `M-x go-run` but my program accepts user input,
since compilation mode is not complete shell it doesn't allow me to
write an input. I've searched and found that `comint-mode` enabled in
compilation buffer could help me. See http://endlessparentheses.com/provide-input-to-the-compilation-buffer.html.
This is my implementation of this feature. I hope it doesn't break your
API.
`C-u M-x go-run` - prompts for arguments using history
`C-u C-u M-x go-run` - run with `comint-mode` enabled
`C-u C-u C-u M-x go-run` - prompts for arguments using history and run with `comint-mode` enabled

Add support for compilation with comint-mode enabled

---

gotest.el

This ensures that whenever gotest.el invokes `go test`, the package `.` is passed on the command line. 
Apparently, the test runner turns on verbosity when it's not given a package to test, so it ignores the `go-test-verbose` flag.
I've run gotest.el with this for a year now (forked off version 0.7! Phew!) - hope this is acceptable (-:

Pass . as the package name in current-{test,file}

---

gotest.el

This change only erases the *Go Test* buffer prior to a run, as opposed
to killing it. This ensures that window/frame arrangements can be made
to show the output buffer in a single place reliably.
I think this should take care of #40 - I have had the same issue. With this change, I can make a `popwin` configuration like this:
``` elisp
(push '(go-test-mode :width 80 :position right :noselect t) popwin:special-display-config)
```
allows me to re-use the buffer and not split windows all the time (in fact, if the test buffer is open in a frame on my second display, it stays there - very convenient!)

Re-use the test output buffer if it is shown

---

gotest.el

`go test --coverprofile cover.out ./...` =>
cannot use test profile flag with multiple packages
Fixed it with `./.`

Fixed test profile multiple packages issue

---

test/gotest-version-test.el
test/test-helper.el

**Note that one of the tests fails, but it is the same test that
also fails without these changes.**
The file isn't a library intended to be loaded with `require`.
Instead `ert-runner` loads it using `load`.  Other packages that
use `ert-runner` also come with a file named test-helper.el and
unfortunately many of those also provide `test-helper`, which
leads to conflicts.

No longer provide a feature in test-helper.el

---

gotest.el
test/gotest-test.el

If go-test-current-file is called from a go file with no corresponding
_test.go file, it will fail with (wrong-type-argument stringp nil).
Catch this before the lisp error is raised and output a friendlier message.

Raise a friendly error if no test file exists

---

gotest.el

Otherwise running go-test-current-test on Foo can result in running
both Foo and FooBar

add missing $ after test name

---

gotest.el

Because we were clobbering the process sentinel defined in compile.el, we
never correctly cleaned up after process exit, including for example
removing the "Compiling" text in the mode line. (We were just leaking the
processes into compilation-in-progress.)
This commit ensures that compilation-sentinel is still invoked.
Maybe a nicer way to do this is to get the existing `process-sentinel` value
and wrap around that, rather than naming the compilation-sentinel directly,
but it adds a perhaps needless amount of complexity for what we actually
want to do here.

Resolves #62 - ensure compilation-sentinel is invoked

---

gotest.el
test/gotest-test.el

Provide a shorthand for passing the -count flag to go test.
For example C-u 1 M-x go-test-current-file will pass -count=1 as the first
argument to `go test`. This is useful because, as of go 1.10, the idiomatic
way to dismiss test caching is to pass -count=1.

Resolves #63 - interpret C-u number as count parameter

---

gotest.el

Fixes this `go-test-current-file` error when no corresponding test file exists:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
expand-file-name(nil)
find-file-noselect(nil)
(let ((filename (ff-other-file-name))) (message "File :%s" filename) (find-file-noselect filename))
(let ((ff-always-try-to-create nil)) (let ((filename (ff-other-file-name))) (message "File :%s" filename) (find-file-noselect filename)))
(if (string-match "_test.go$" buffer-file-name) (current-buffer) (let ((ff-always-try-to-create nil)) (let ((filename (ff-other-file-name))) (message "File :%s" filename) (find-file-noselect filename))))
go-test--get-current-buffer()
(set-buffer (go-test--get-current-buffer))
(save-current-buffer (set-buffer (go-test--get-current-buffer)) (save-excursion (goto-char …
```

Handle non-existing test buffers gracefully

---

README.md
gotest.el

Please, see the following ticket https://github.com/nlamirault/gotest.el/issues/72

Rerun current test with go-test-current-test-cache()

---

gotest.el

Additional arguments should be added as the last commandline
arguments. Currently it adds them between test name and `\$`.
For example, if additional arguments are set to `-count=1` command
line will be creates as follows:
```
go test -run TestSomeTest-count=1 \$ . -v
```
After the fix:
```
go test -run TestSomeTest\$ . -count=1  -v
```

Fix order of commandline arguments concatenation

---

gotest.el

This fixes the order of arguments.  When running a single testify test with `go-test-args` set to "-race" to enable the race checker, I was getting the following command:
``` sh
go test -testify.m TestRelationsRace\$ . -race
```
This caused the -race flag to be ignored; it is supposed to be before the package name.  This PR changes the order of the arguments so this command is now generated as:
```sh
go test -race -testify.m TestRelationsRace\$ . 
```
which works properly.

Put any extra arguments from go-test-args before the test name

---

gotest.el

Originally this was just `-m`, but was namespaced to `-testify.m` 2 years
ago, in https://github.com/stretchr/testify/commit/bfe70f3776f95c8c83debfde6ea754ab62a147d2
This commit updates the suite aware flag to use the namespaced version. This
will be a breaking change if you're using a testify from > 2 years ago, but
on the flip side, it's currently broken if you're using something more
recent than that!

resolves #67 -- use namespaced testify flag

---

gotest.el

Since `ff-other-file-name` has been deleted.

Used ff-get-other-file to find the test buffer

---

gotest.el

They can be set via `.dir-locals.el` to something like `docker-compose --ansi=never run --rm test go` when working with a Docker-based development environment.

Add go-test-go-command and go-run-go-command buffer-local variables

---

gotest.el

In case gotest can work correctly together with go-ts-mode, go tree-sitter mode shipped with emacs 29.

Removed go-mode dependency
